// RideSense Seed Data & System State
// "Smart Travel. Smarter Buses. Better Journeys."
const RideSenseData = {
  appName: "RideSense",
tagline: "Smarter Routes, Safer Journeys"
  // Transit Regions & Corridors
  corridors: [
    { id: "all", name: "All Routes & Corridors", nameTa: "அனைத்து வழித்தடங்களும்", nameHi: "सभी मार्ग और गलियारे" },
    { id: "kanyakumari-tourist", name: "Kanyakumari Tourist Network", nameTa: "கன்னியாகுமரி சுற்றுலா வலைப்பின்னல்", nameHi: "कन्याकुमारी पर्यटक नेटवर्क" },
    { id: "junction-palai", name: "Junction – Palayamkottai Corridor", nameTa: "சந்திப்பு – பாளையங்கோட்டை தடம்", nameHi: "जंक्शन – पालयमकोट्टई गलियारा" },
    { id: "medical-express", name: "High Ground Medical Corridor", nameTa: "மருத்துவக் கல்லூரி விரைவு தடம்", nameHi: "मेडिकल कॉलेज एक्सप्रेस गलियारा" },
    { id: "pettai-ind", name: "Pettai Industrial Corridor", nameTa: "பேட்டை தொழில் வழித்தடம்", nameHi: "पेट्टई औद्योगिक गलियारा" }
  ],

  // 13 Iconic Kanyakumari Tourist Places & Landmarks
  touristPlaces: [
    {
      id: "place_1",
      name: "Vivekananda Rock Memorial",
      nameTa: "விவேகானந்தர் பாறை நினைவு மண்டபம்",
      nameHi: "विवेकानंद रॉक मेमोरियल",
      category: "Tourist Place",
      lat: 8.0780,
      lng: 77.5552,
      nearestStopId: "stop_kk_ferry",
      nearestStopName: "Kanyakumari Ferry Area / Jetty",
      recommendedBusId: "1A",
      walkingDistance: "450 m",
      journeyTime: "12 min",
      description: "Iconic ocean monument situated on an offshore rock where Swami Vivekananda attained enlightenment.",
      descriptionTa: "கடல் நடுவே அமைந்துள்ள உலகப் புகழ்பெற்ற வரலாற்றுச் சிறப்புமிக்க நினைவு மண்டபம்.",
      descriptionHi: "समुद्र के बीच एक चट्टान पर स्थित प्रसिद्ध स्मारक जहाँ स्वामी विवेकानंद ने ध्यान किया था।",
      approxVisitTime: "2 hours",
      entryFee: "Demo Entry: ₹20 + Ferry ₹50",
      image: "fa-landmark-dome"
    },
    {
      id: "place_2",
      name: "Thiruvalluvar Statue",
      nameTa: "திருவள்ளுவர் சிலை",
      nameHi: "तिरुवल्लुवर प्रतिमा",
      category: "Tourist Place",
      lat: 8.0770,
      lng: 77.5540,
      nearestStopId: "stop_kk_ferry",
      nearestStopName: "Kanyakumari Ferry Area / Jetty",
      recommendedBusId: "1A",
      walkingDistance: "450 m",
      journeyTime: "12 min",
      description: "Magnificent 133-feet stone sculpture of the legendary Tamil poet-philosopher Thiruvalluvar.",
      descriptionTa: "133 அடி உயரமுள்ள உலகப் புகழ்பெற்ற மாபெரும் தமிழ்ப்புலவர் திருவள்ளுவர் கற்சிலை.",
      descriptionHi: "तमिल कवि और दार्शनिक संत तिरुवल्लुवर की 133 फीट ऊंची भव्य पाषाण प्रतिमा।",
      approxVisitTime: "1 hour",
      entryFee: "Included in Ferry",
      image: "fa-monument"
    },
    {
      id: "place_3",
      name: "Kanyakumari Beach & Triveni Sangam",
      nameTa: "கன்னியாகுமரி கடற்கரை & முக்கடல் சங்கமம்",
      nameHi: "कन्याकुमारी बीच और त्रिवेणी संगम",
      category: "Tourist Place",
      lat: 8.0815,
      lng: 77.5510,
      nearestStopId: "stop_kk_beach",
      nearestStopName: "Kanyakumari Beach Stop",
      recommendedBusId: "1A",
      walkingDistance: "200 m",
      journeyTime: "6 min",
      description: "Spectacular confluence of the Indian Ocean, Arabian Sea, and Bay of Bengal with multi-colored sand.",
      descriptionTa: "இந்தியப் பெருங்கடல், அரபிக்கடல் மற்றும் வங்காள விரிகுடா சங்கமிக்கும் அழகிய கடற்கரை.",
      descriptionHi: "तीन समुद्रों (हिंद महासागर, अरब सागर और बंगाल की खाड़ी) का अनूठा संगम स्थल।",
      approxVisitTime: "1.5 hours",
      entryFee: "Free Public Access",
      image: "fa-umbrella-beach"
    },
    {
      id: "place_4",
      name: "Sunset Point (Hidden Beach)",
      nameTa: "சூரிய அஸ்தமன முனை (சன்செட் பாயிண்ட்)",
      nameHi: "सनसेट पॉइंट (सूर्यास्त दृश्य)",
      category: "Tourist Place",
      lat: 8.0850,
      lng: 77.5350,
      nearestStopId: "stop_kk_sunset",
      nearestStopName: "Sunset Point Stop",
      recommendedBusId: "4B",
      walkingDistance: "300 m",
      journeyTime: "15 min",
      description: "Premier vantage point for witnessing the breathtaking ocean sunset across the Arabian Sea horizon.",
      descriptionTa: "அரபிக்கடல் அடிவானில் சூரியன் மறையும் கண்கொள்ளாக் காட்சியை கண்டு ரசிக்க சிறந்த இடம்.",
      descriptionHi: "अरब सागर में डूबते सूर्य का विहंगम दृश्य देखने का सबसे लोकप्रिय स्थान।",
      approxVisitTime: "1 hour",
      entryFee: "Free",
      image: "fa-sun"
    },
    {
      id: "place_5",
      name: "Sunrise Point (View Tower)",
      nameTa: "சூரிய உதய முனை (சன்ரைஸ் பாயிண்ட்)",
      nameHi: "सनराइज पॉइंट (सूर्योदय दृश्य)",
      category: "Tourist Place",
      lat: 8.0840,
      lng: 77.5560,
      nearestStopId: "stop_kk_beach",
      nearestStopName: "Kanyakumari Beach Stop",
      recommendedBusId: "1A",
      walkingDistance: "350 m",
      journeyTime: "8 min",
      description: "Breathtaking coastal spot to witness the morning sun rising out of the Bay of Bengal waters.",
      descriptionTa: "வங்காள விரிகுடாவில் சூரியன் உதயமாவதை ரசிக்க அமைக்கப்பட்ட பார்வை கோபுரம்.",
      descriptionHi: "बंगाल की खाड़ी के ऊपर सूर्योदय का मनमोहक दृश्य देखने का प्रमुख स्थान।",
      approxVisitTime: "45 mins",
      entryFee: "Free / Tower ₹10",
      image: "fa-cloud-sun"
    },
    {
      id: "place_6",
      name: "Bhagavathi Amman Temple",
      nameTa: "கன்னியாகுமரி பகவதி அம்மன் கோவில்",
      nameHi: "भगवती अम्मन मंदिर",
      category: "Landmarks",
      lat: 8.0805,
      lng: 77.5515,
      nearestStopId: "stop_kk_beach",
      nearestStopName: "Kanyakumari Beach Stop",
      recommendedBusId: "1A",
      walkingDistance: "250 m",
      journeyTime: "7 min",
      description: "Ancient 3,000-year-old sacred coastal temple dedicated to Goddess Kanya Kumari with sparkling diamond nose-ring.",
      descriptionTa: "மூவாயிரம் ஆண்டுகள் பழமையான புகழ்பெற்ற அம்மன் சக்திபீட திருத்தலம்.",
      descriptionHi: "देवी कन्याकुमारी को समर्पित 3000 वर्ष पुराना अत्यंत पावन एवं प्राचीन शक्तिपीठ मंदिर।",
      approxVisitTime: "1 hour",
      entryFee: "Free Temple Entry",
      image: "fa-gopuram"
    },
    {
      id: "place_7",
      name: "Gandhi Memorial Mandapam",
      nameTa: "மகாத்மா காந்தி நினைவு மண்டபம்",
      nameHi: "गांधी मेमोरियल मंडपम",
      category: "Landmarks",
      lat: 8.0820,
      lng: 77.5530,
      nearestStopId: "stop_kk_gandhi",
      nearestStopName: "Gandhi Mandapam Stop",
      recommendedBusId: "1A",
      walkingDistance: "150 m",
      journeyTime: "5 min",
      description: "Architectural memorial designed such that sun rays fall directly upon Mahatma Gandhi's memorial spot on Oct 2nd.",
      descriptionTa: "அக்டோபர் 2 அன்று சூரியக் கதிர்கள் காந்தியடிகளின் அஸ்தி பீடத்தில் படும் வகையில் கட்டப்பட்ட மண்டபம்.",
      descriptionHi: "महात्मा गांधी की अस्थि कलश स्मृति में बना अद्वितीय वास्तुकला वाला भव्य स्मारक।",
      approxVisitTime: "45 mins",
      entryFee: "Free Entry",
      image: "fa-landmark"
    },
    {
      id: "place_8",
      name: "Suchindram Thanumalayan Temple",
      nameTa: "சுசீந்திரம் தாணுமாலயன் கோவில்",
      nameHi: "सुचिंद्रम थानुमलयन मंदिर",
      category: "Landmarks",
      lat: 8.1565,
      lng: 77.4650,
      nearestStopId: "stop_kk_suchindram",
      nearestStopName: "Suchindram Junction Stop",
      recommendedBusId: "2A",
      walkingDistance: "200 m",
      journeyTime: "25 min",
      description: "Architectural marvel worshipping the Trinity (Brahma, Vishnu, Shiva) with musical pillars and 22-ft Hanuman statue.",
      descriptionTa: "மும்மூர்த்திகளும் ஒருங்கே அருளும் இசைத் தூண்கள் மற்றும் பிரம்மாண்ட அனுமன் சிலை கொண்ட கோவில்.",
      descriptionHi: "ब्रह्मा, विष्णु और महेश के त्रिमूर्ति स्वरूप को समर्पित प्रसिद्ध मंदिर, संगीतमय स्तंभों हेतु विख्यात।",
      approxVisitTime: "1.5 hours",
      entryFee: "Free Temple Entry",
      image: "fa-place-of-worship"
    },
    {
      id: "place_9",
      name: "Vattakottai Fort (Circular Seaside Fort)",
      nameTa: "வட்டக்கோட்டை கடல் கோட்டை",
      nameHi: "वट्टाकोट्टई किला (तटीय दुर्ग)",
      category: "Tourist Place",
      lat: 8.1250,
      lng: 77.5650,
      nearestStopId: "stop_kk_vatta",
      nearestStopName: "Vattakottai Fort Stop",
      recommendedBusId: "2B",
      walkingDistance: "250 m",
      journeyTime: "20 min",
      description: "18th-century granite coastal fort built by Travancore kingdom offering panoramic panoramic sea breeze and hill views.",
      descriptionTa: "திருவிதாங்கூர் மன்னர்களால் கட்டப்பட்ட கடலை நோக்கிய எழில் கொஞ்சும் 18-ஆம் நூற்றாண்டு கருங்கல் கோட்டை.",
      descriptionHi: "18वीं सदी का तटीय ग्रेनाइट किला, जहाँ से शांत नीले समुद्र और पश्चिमी घाट का मनमोहक दृश्य दिखता है।",
      approxVisitTime: "1.5 hours",
      entryFee: "₹25 Entry",
      image: "fa-shield-halved"
    },
    {
      id: "place_10",
      name: "Padmanabhapuram Palace",
      nameTa: "பத்மநாபபுரம் அரண்மனை",
      nameHi: "पद्मनाभपुरम महल",
      category: "Tourist Place",
      lat: 8.2510,
      lng: 77.3275,
      nearestStopId: "stop_kk_padma",
      nearestStopName: "Thuckalay / Padmanabhapuram Bus Stop",
      recommendedBusId: "2C",
      walkingDistance: "400 m",
      journeyTime: "50 min",
      description: "One of Asia's finest wooden palaces featuring traditional Kerala-style intricate woodwork and antique artifacts.",
      descriptionTa: "ஆசியாவின் தலைசிறந்த மரத்தாலான அரண்மனை, நுணுக்கமான மர வேலைப்பாடுகள் கொண்டது.",
      descriptionHi: "पारंपरिक केरल शैली में निर्मित एशिया का बेहतरीन लकड़ी का राजमहल, अनूठी नक्काशी हेतु विख्यात।",
      approxVisitTime: "2 hours",
      entryFee: "₹50 (Demo)",
      image: "fa-chess-rook"
    },
    {
      id: "place_11",
      name: "Mathur Hanging Aqueduct",
      nameTa: "மாத்தூர் தொங்கு பாலம் (நீர்நிலை பாலம்)",
      nameHi: "माथुर हैंगिंग एक्वाडक्ट",
      category: "Tourist Place",
      lat: 8.3320,
      lng: 77.2950,
      nearestStopId: "stop_kk_mathur",
      nearestStopName: "Mathur Bridge Stop",
      recommendedBusId: "2C",
      walkingDistance: "300 m",
      journeyTime: "60 min",
      description: "Longest and highest flume aqueduct in South Asia offering sensational green valley views between two lush hills.",
      descriptionTa: "தெற்காசியாவின் மிக நீளமான மற்றும் உயரமான தொங்கு கால்வாய் பாலம்.",
      descriptionHi: "दक्षिण एशिया का सबसे लंबा और ऊंचा एक्वाडक्ट पुल, हरे-भरे पहाड़ों के बीच से गुजरने वाला विस्मयकारी दृश्य।",
      approxVisitTime: "1 hour",
      entryFee: "₹10",
      image: "fa-water"
    },
    {
      id: "place_12",
      name: "Kanyakumari Railway Station",
      nameTa: "கன்னியாகுமரி ரயில் நிலையம்",
      nameHi: "कन्याकुमारी रेलवे स्टेशन",
      category: "Stations",
      lat: 8.0890,
      lng: 77.5480,
      nearestStopId: "stop_kk_station",
      nearestStopName: "Kanyakumari Railway Station",
      recommendedBusId: "3B",
      walkingDistance: "100 m",
      journeyTime: "4 min",
      description: "Southernmost terminal railway station of mainland India connecting express trains across the nation.",
      descriptionTa: "இந்திய பெருநிலத்தின் தென்கோடி ரயில்வே முனையம்.",
      descriptionHi: "भारत की मुख्य भूमि का सबसे दक्षिणी रेलवे स्टेशन।",
      approxVisitTime: "30 mins",
      entryFee: "Platform Ticket ₹10",
      image: "fa-train"
    },
    {
      id: "place_13",
      name: "Kanyakumari Central Bus Stand",
      nameTa: "கன்னியாகுமரி மத்திய பேருந்து நிலையம்",
      nameHi: "कन्याकुमारी सेंट्रल बस स्टैंड",
      category: "Bus Stops",
      lat: 8.0880,
      lng: 77.5450,
      nearestStopId: "stop_kk_stand",
      nearestStopName: "Kanyakumari Bus Stand",
      recommendedBusId: "1A",
      walkingDistance: "50 m",
      journeyTime: "2 min",
      description: "Primary municipal and interstate transit terminus for government and tourist buses.",
      descriptionTa: "கன்னியாகுமரியின் பிரதான அரசு மற்றும் சுற்றுலா பேருந்து முனையம்.",
      descriptionHi: "कन्याकुमारी का मुख्य सार्वजनिक बस स्टैंड, सभी स्थानीय एवं अंतरराज्यीय मार्गों का केंद्र।",
      approxVisitTime: "N/A",
      entryFee: "Public Access",
      image: "fa-bus"
    }
  ],

  // Comprehensive Bus Stops (Kanyakumari + Tirunelveli smart network)
  stops: [
    // Kanyakumari Transit Network
    { id: "stop_kk_stand", name: "Kanyakumari Bus Stand", nameTa: "கன்னியாகுமரி பேருந்து நிலையம்", nameHi: "कन्याकुमारी बस स्टैंड", lat: 8.0880, lng: 77.5450, bay: "Bay 1 (Tourist Hub)" },
    { id: "stop_kk_station", name: "Kanyakumari Railway Station", nameTa: "கன்னியாகுமரி ரயில் நிலையம்", nameHi: "कन्याकुमारी रेलवे स्टेशन", lat: 8.0890, lng: 77.5480, bay: "Station Porch Stop" },
    { id: "stop_kk_beach", name: "Kanyakumari Beach Stop", nameTa: "கன்னியாகுமரி கடற்கரை", nameHi: "कन्याकुमारी बीच स्टॉप", lat: 8.0815, lng: 77.5510, bay: "Beach Pavilion" },
    { id: "stop_kk_gandhi", name: "Gandhi Mandapam / Memorial", nameTa: "காந்தி மண்டபம்", nameHi: "गांधी मंडपम", lat: 8.0820, lng: 77.5530, bay: "Memorial Bay" },
    { id: "stop_kk_ferry", name: "Kanyakumari Ferry Area / Jetty", nameTa: "படகுத்துறை / விவேகானந்தர் பாறை", nameHi: "फेरी क्षेत्र / जेटी", lat: 8.0790, lng: 77.5535, bay: "Jetty Plaza" },
    { id: "stop_kk_sunset", name: "Sunset Point (Hidden Beach)", nameTa: "சன்செட் பாயிண்ட்", nameHi: "सनसेट पॉइंट", lat: 8.0850, lng: 77.5350, bay: "Sunset View Stop" },
    { id: "stop_kk_suchindram", name: "Suchindram Temple Junction", nameTa: "சுசீந்திரம் சந்திப்பு", nameHi: "सुचिंद्रम मंदिर जंक्शन", lat: 8.1565, lng: 77.4650, bay: "Temple Arch Bay" },
    { id: "stop_kk_vatta", name: "Vattakottai Fort Stop", nameTa: "வட்டக்கோட்டை நிறுத்தம்", nameHi: "वट्टाकोट्टई फोर्ट स्टॉप", lat: 8.1250, lng: 77.5650, bay: "Fort Entrance" },
    { id: "stop_kk_padma", name: "Thuckalay / Padmanabhapuram", nameTa: "தக்கலை / பத்மநாபபுரம்", nameHi: "थकलाई / पद्मनाभपुरम", lat: 8.2510, lng: 77.3275, bay: "Palace Road" },
    { id: "stop_kk_mathur", name: "Mathur Hanging Bridge", nameTa: "மாத்தூர் தொங்கு பாலம்", nameHi: "माथुर हैंगिंग ब्रिज", lat: 8.3320, lng: 77.2950, bay: "Aqueduct Stop" },
    { id: "stop_kk_nagercoil", name: "Nagercoil Christopher Bus Stand", nameTa: "நாகர்கோவில் கிறிஸ்டோபர் பேருந்து நிலையம்", nameHi: "नागरकोइल बस स्टैंड", lat: 8.1830, lng: 77.4110, bay: "Platform 4" },

    // Tirunelveli Transit Network
    { id: "stop_1", name: "Tirunelveli Junction Bus Stand", nameTa: "திருநெல்வேலி சந்திப்பு பேருந்து நிலையம்", nameHi: "तिरुनेलवेली जंक्शन बस स्टैंड", lat: 8.7295, lng: 77.7082, bay: "Bay 3" },
    { id: "stop_2", name: "Vannarpettai Checkpost", nameTa: "வண்ணாரப்பேட்டை சோதனைச்சாவடி", nameHi: "वन्नारपेट्टई चेकपोस्ट", lat: 8.7245, lng: 77.7215, bay: "Stop A" },
    { id: "stop_3", name: "Murugankurichi Signal", nameTa: "முருகன்குறிச்சி சிக்னல்", nameHi: "मुरुगंकुरिची सिग्नल", lat: 8.7198, lng: 77.7310, bay: "Stop B" },
    { id: "stop_4", name: "Palayamkottai Bus Stand / Market", nameTa: "பாளையங்கோட்டை பேருந்து நிலையம்", nameHi: "पालयमकोट्टई बस स्टैंड / मार्केट", lat: 8.7125, lng: 77.7430, bay: "Bay 1" },
    { id: "stop_5", name: "Government Medical College Hospital", nameTa: "அரசு மருத்துவக் கல்லூரி மருத்துவமனை", nameHi: "सरकारी मेडिकल कॉलेज अस्पताल", lat: 8.7050, lng: 77.7555, bay: "Bay 2" },
    { id: "stop_6", name: "Pettai Industrial Estate", nameTa: "பேட்டை தொழிற்பேட்டை", nameHi: "पेट्टई औद्योगिक एस्टेट", lat: 8.7420, lng: 77.6820, bay: "Bay 4" },
    { id: "stop_7", name: "Tirunelveli Town Nellaiyappar Temple", nameTa: "நெல்லையப்பர் கோவில்", nameHi: "नेल्लैयाप्पर मंदिर", lat: 8.7350, lng: 77.6980, bay: "Stop C" },
    { id: "stop_8", name: "New Bus Stand (Vaeinthaankulam)", nameTa: "புதிய பேருந்து நிலையம்", nameHi: "नया बस स्टैंड", lat: 8.7080, lng: 77.7190, bay: "Bay 5" }
  ],

  // Full Simulated Fleet (Kanyakumari Tourist Routes + City Services)
  buses: [
    // --- KANYAKUMARI TOURIST BUSES (1A to 4B) ---
    {
      id: "1A",
      regNo: "TN-74-N-0101",
      routeNo: "1A",
      routeName: "Kanyakumari Tourist Loop",
      routeNameTa: "கன்னியாகுமரி சுற்றுலா சுற்றுப்பாதை",
      routeNameHi: "कन्याकुमारी पर्यटक लूप",
      origin: "Kanyakumari Bus Stand",
      destination: "Vivekananda Ferry & Beach",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Tourist Special Circular",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 22,
      seated: 20,
      standing: 2,
      availableSeats: 12,
      crowdPercentage: 44,
      crowdLevel: "comfortable", // comfortable, moderate, crowded, overcrowded
      currentSpeed: 28,
      etaMinutes: 4,
      currentStopIndex: 0,
      currentStop: "Kanyakumari Bus Stand",
      nextStop: "Kanyakumari Beach",
      previousStop: "Starting Terminus",
      currentLocation: { lat: 8.0870, lng: 77.5460 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "On time / Tourist priority corridor",
      routeDeviation: false,
      sectionCrowd: { front: 38, middle: 48, rear: 42 },
      doorStatus: {
        frontDoorCrowd: 32,
        middleDoorCrowd: 40,
        rearDoorCrowd: 28,
        isSafeToDepart: true,
        warningMessage: "All doors clear. Comfortable boarding for tourists and families."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_beach", "stop_kk_gandhi", "stop_kk_ferry", "stop_kk_sunset"],
      driverName: "R. Manikandan",
      driverRating: 4.9,
      conductorName: "K. Selvam",
      platformBay: "Bay 1 (Tourist Stand)",
      approxJourneyTime: "25 min"
    },
    {
      id: "1B",
      regNo: "TN-74-N-0102",
      routeNo: "1B",
      routeName: "Kanyakumari → Nagercoil Express",
      routeNameTa: "கன்னியாகுமரி → நாகர்கோவில் விரைவு",
      routeNameHi: "कन्याकुमारी → नागरकोइल एक्सप्रेस",
      origin: "Kanyakumari Bus Stand",
      destination: "Nagercoil Christopher Bus Stand",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Semi-Deluxe Express",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 44,
      seated: 32,
      standing: 12,
      availableSeats: 0,
      crowdPercentage: 88,
      crowdLevel: "crowded",
      currentSpeed: 42,
      etaMinutes: 8,
      currentStopIndex: 1,
      currentStop: "Kanyakumari Bus Stand",
      nextStop: "Suchindram Temple Junction",
      previousStop: "Starting Terminus",
      currentLocation: { lat: 8.1150, lng: 77.5100 },
      baseFare: 22,
      studentFare: 8,
      seniorFare: 15,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 3,
      delayReason: "Suchindram junction traffic queue",
      routeDeviation: false,
      sectionCrowd: { front: 85, middle: 92, rear: 86 },
      doorStatus: {
        frontDoorCrowd: 82,
        middleDoorCrowd: 90,
        rearDoorCrowd: 84,
        isSafeToDepart: false,
        warningMessage: "High passenger boarding count. Doorway heavily occupied."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_suchindram", "stop_kk_nagercoil"],
      driverName: "S. Rajan",
      driverRating: 4.75,
      conductorName: "P. Murugan",
      platformBay: "Bay 3 (Nagercoil Platform)",
      approxJourneyTime: "40 min"
    },
    {
      id: "1C",
      regNo: "TN-74-N-0103",
      routeNo: "1C",
      routeName: "Nagercoil → Kanyakumari Direct",
      routeNameTa: "நாகர்கோவில் → கன்னியாகுமரி நேரடி",
      routeNameHi: "नागरकोइल → कन्याकुमारी डायरेक्ट",
      origin: "Nagercoil Christopher Bus Stand",
      destination: "Kanyakumari Bus Stand",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "City Regular",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 30,
      seated: 24,
      standing: 6,
      availableSeats: 8,
      crowdPercentage: 60,
      crowdLevel: "comfortable",
      currentSpeed: 36,
      etaMinutes: 14,
      currentStopIndex: 0,
      currentStop: "Nagercoil Christopher Bus Stand",
      nextStop: "Suchindram Temple Junction",
      previousStop: "Starting Terminus",
      currentLocation: { lat: 8.1650, lng: 77.4400 },
      baseFare: 20,
      studentFare: 7,
      seniorFare: 14,
      acBus: false,
      wheelchairAccessible: false,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "On time",
      routeDeviation: false,
      sectionCrowd: { front: 55, middle: 64, rear: 58 },
      doorStatus: {
        frontDoorCrowd: 48,
        middleDoorCrowd: 55,
        rearDoorCrowd: 44,
        isSafeToDepart: true,
        warningMessage: "Doors clear. Boarding operating smoothly."
      },
      stopsServed: ["stop_kk_nagercoil", "stop_kk_suchindram", "stop_kk_stand"],
      driverName: "V. Thangaraj",
      driverRating: 4.8,
      conductorName: "M. Kumar",
      platformBay: "Bay 2",
      approxJourneyTime: "38 min"
    },
    {
      id: "2A",
      regNo: "TN-74-N-0201",
      routeNo: "2A",
      routeName: "Kanyakumari → Suchindram Heritage Line",
      routeNameTa: "கன்னியாகுமரி → சுசீந்திரம் ஆன்மீகப் பாதை",
      routeNameHi: "कन्याकुमारी → सुचिंद्रम हेरिटेज लाइन",
      origin: "Kanyakumari Bus Stand",
      destination: "Suchindram Temple",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Heritage Special",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 19,
      seated: 18,
      standing: 1,
      availableSeats: 14,
      crowdPercentage: 38,
      crowdLevel: "comfortable",
      currentSpeed: 34,
      etaMinutes: 6,
      currentStopIndex: 0,
      currentStop: "Kanyakumari Bus Stand",
      nextStop: "Suchindram Temple Junction",
      previousStop: "Starting Terminus",
      currentLocation: { lat: 8.0950, lng: 77.5350 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "On time",
      routeDeviation: false,
      sectionCrowd: { front: 32, middle: 42, rear: 36 },
      doorStatus: {
        frontDoorCrowd: 25,
        middleDoorCrowd: 35,
        rearDoorCrowd: 22,
        isSafeToDepart: true,
        warningMessage: "Plenty of seats vacant. Ideal for elderly pilgrims and families."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_station", "stop_kk_suchindram"],
      driverName: "P. Sundaram",
      driverRating: 4.95,
      conductorName: "N. Annamalai",
      platformBay: "Bay 5 (Heritage Bay)",
      approxJourneyTime: "25 min"
    },
    {
      id: "2B",
      regNo: "TN-74-N-0202",
      routeNo: "2B",
      routeName: "Kanyakumari → Vattakottai Coastal Fort",
      routeNameTa: "கன்னியாகுமரி → வட்டக்கோட்டை கடற்கரை",
      routeNameHi: "कन्याकुमारी → वट्टाकोट्टई कोस्टल फोर्ट",
      origin: "Kanyakumari Bus Stand",
      destination: "Vattakottai Fort",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Tourist Shuttle",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 26,
      seated: 22,
      standing: 4,
      availableSeats: 10,
      crowdPercentage: 52,
      crowdLevel: "comfortable",
      currentSpeed: 32,
      etaMinutes: 10,
      currentStopIndex: 0,
      currentStop: "Kanyakumari Bus Stand",
      nextStop: "Vattakottai Fort Stop",
      previousStop: "Starting Terminus",
      currentLocation: { lat: 8.1020, lng: 77.5580 },
      baseFare: 18,
      studentFare: 6,
      seniorFare: 12,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "Coastal route clear",
      routeDeviation: false,
      sectionCrowd: { front: 48, middle: 56, rear: 50 },
      doorStatus: {
        frontDoorCrowd: 40,
        middleDoorCrowd: 48,
        rearDoorCrowd: 38,
        isSafeToDepart: true,
        warningMessage: "Doors clear. Boarding comfortable."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_beach", "stop_kk_vatta"],
      driverName: "D. Velu",
      driverRating: 4.8,
      conductorName: "T. Ganesan",
      platformBay: "Bay 6",
      approxJourneyTime: "22 min"
    },
    {
      id: "2C",
      regNo: "TN-74-N-0203",
      routeNo: "2C",
      routeName: "Kanyakumari → Padmanabhapuram Palace",
      routeNameTa: "கன்னியாகுமரி → பத்மநாபபுரம் அரண்மனை",
      routeNameHi: "कन्याकुमारी → पद्मनाभपुरम पैलेस",
      origin: "Kanyakumari Bus Stand",
      destination: "Padmanabhapuram Palace & Mathur",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Superfast Tourist Deluxe",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 34,
      seated: 26,
      standing: 8,
      availableSeats: 6,
      crowdPercentage: 68,
      crowdLevel: "moderate",
      currentSpeed: 45,
      etaMinutes: 18,
      currentStopIndex: 1,
      currentStop: "Suchindram Temple Junction",
      nextStop: "Thuckalay / Padmanabhapuram",
      previousStop: "Kanyakumari Bus Stand",
      currentLocation: { lat: 8.1900, lng: 77.4000 },
      baseFare: 30,
      studentFare: 10,
      seniorFare: 20,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 2,
      delayReason: "Thuckalay bazaar bottleneck",
      routeDeviation: false,
      sectionCrowd: { front: 62, middle: 74, rear: 66 },
      doorStatus: {
        frontDoorCrowd: 55,
        middleDoorCrowd: 65,
        rearDoorCrowd: 50,
        isSafeToDepart: true,
        warningMessage: "Moderate crowd. Seating available."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_suchindram", "stop_kk_padma", "stop_kk_mathur"],
      driverName: "A. Pandian",
      driverRating: 4.9,
      conductorName: "J. Peter",
      platformBay: "Bay 7",
      approxJourneyTime: "55 min"
    },
    {
      id: "3A",
      regNo: "TN-74-N-0301",
      routeNo: "3A",
      routeName: "Kanyakumari Tourist Circular",
      routeNameTa: "கன்னியாகுமரி சுற்றுலா சுற்றுப் பேருந்து",
      routeNameHi: "कन्याकुमारी पर्यटक परिपत्र",
      origin: "Kanyakumari Bus Stand",
      destination: "All Tourist Landmarks Circular",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Hop-On Hop-Off Tourist Shuttle",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 24,
      seated: 22,
      standing: 2,
      availableSeats: 10,
      crowdPercentage: 48,
      crowdLevel: "comfortable",
      currentSpeed: 25,
      etaMinutes: 5,
      currentStopIndex: 1,
      currentStop: "Kanyakumari Beach",
      nextStop: "Gandhi Mandapam / Memorial",
      previousStop: "Kanyakumari Bus Stand",
      currentLocation: { lat: 8.0825, lng: 77.5520 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "On time",
      routeDeviation: false,
      sectionCrowd: { front: 42, middle: 52, rear: 46 },
      doorStatus: {
        frontDoorCrowd: 38,
        middleDoorCrowd: 45,
        rearDoorCrowd: 35,
        isSafeToDepart: true,
        warningMessage: "Hop-on Hop-off service running smoothly."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_beach", "stop_kk_gandhi", "stop_kk_ferry", "stop_kk_sunset"],
      driverName: "C. Balan",
      driverRating: 4.85,
      conductorName: "M. Raman",
      platformBay: "Bay 1 (Hop-On Station)",
      approxJourneyTime: "30 min"
    },
    {
      id: "3B",
      regNo: "TN-74-N-0302",
      routeNo: "3B",
      routeName: "Beach → Railway Station → Bus Stand",
      routeNameTa: "கடற்கரை → ரயில் நிலையம் → பேருந்து நிலையம்",
      routeNameHi: "बीच → रेलवे स्टेशन → बस स्टैंड",
      origin: "Kanyakumari Beach",
      destination: "Kanyakumari Bus Stand",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Station Feeder Bus",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 28,
      seated: 24,
      standing: 4,
      availableSeats: 8,
      crowdPercentage: 56,
      crowdLevel: "comfortable",
      currentSpeed: 26,
      etaMinutes: 4,
      currentStopIndex: 0,
      currentStop: "Kanyakumari Beach",
      nextStop: "Kanyakumari Railway Station",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.0840, lng: 77.5500 },
      baseFare: 10,
      studentFare: 4,
      seniorFare: 8,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "Running on schedule",
      routeDeviation: false,
      sectionCrowd: { front: 50, middle: 60, rear: 54 },
      doorStatus: {
        frontDoorCrowd: 42,
        middleDoorCrowd: 50,
        rearDoorCrowd: 40,
        isSafeToDepart: true,
        warningMessage: "Feeder service active."
      },
      stopsServed: ["stop_kk_beach", "stop_kk_station", "stop_kk_stand"],
      driverName: "K. Antony",
      driverRating: 4.7,
      conductorName: "S. Mani",
      platformBay: "Beach Pavilion Bay",
      approxJourneyTime: "15 min"
    },
    {
      id: "4A",
      regNo: "TN-74-N-0401",
      routeNo: "4A",
      routeName: "Kanyakumari → Ferry Area / Vivekananda Rock",
      routeNameTa: "கன்னியாகுமரி → படகுத்துறை / விவேகானந்தர் பாறை",
      routeNameHi: "कन्याकुमारी → फेरी क्षेत्र / विवेकानंद रॉक",
      origin: "Kanyakumari Bus Stand",
      destination: "Kanyakumari Ferry Area / Jetty",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Ferry Shuttle",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 46,
      seated: 32,
      standing: 14,
      availableSeats: 0,
      crowdPercentage: 92,
      crowdLevel: "overcrowded",
      currentSpeed: 20,
      etaMinutes: 3,
      currentStopIndex: 0,
      currentStop: "Kanyakumari Bus Stand",
      nextStop: "Kanyakumari Ferry Area / Jetty",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.0830, lng: 77.5480 },
      baseFare: 10,
      studentFare: 4,
      seniorFare: 8,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 5,
      delayReason: "High tourist morning queue for Vivekananda Memorial ferry",
      routeDeviation: false,
      sectionCrowd: { front: 90, middle: 96, rear: 91 },
      doorStatus: {
        frontDoorCrowd: 88,
        middleDoorCrowd: 94,
        rearDoorCrowd: 89,
        isSafeToDepart: false,
        warningMessage: "Overcrowded ferry shuttle! Boarding lock recommended."
      },
      stopsServed: ["stop_kk_stand", "stop_kk_gandhi", "stop_kk_ferry"],
      driverName: "M. Muthu",
      driverRating: 4.65,
      conductorName: "P. Chellappa",
      platformBay: "Bay 1",
      approxJourneyTime: "12 min"
    },
    {
      id: "4B",
      regNo: "TN-74-N-0402",
      routeNo: "4B",
      routeName: "Sunset Point → Gandhi Mandapam Express",
      routeNameTa: "சன்செட் பாயிண்ட் → காந்தி மண்டபம் விரைவு",
      routeNameHi: "सनसेट पॉइंट → गांधी मंडपम एक्सप्रेस",
      origin: "Sunset Point (Hidden Beach)",
      destination: "Gandhi Mandapam / Beach",
      corridorId: "kanyakumari-tourist",
      isTouristFriendly: true,
      isVerifiedRoute: true,
      serviceType: "Sunset Tourist Cruiser",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 20,
      seated: 18,
      standing: 2,
      availableSeats: 14,
      crowdPercentage: 40,
      crowdLevel: "comfortable",
      currentSpeed: 30,
      etaMinutes: 7,
      currentStopIndex: 0,
      currentStop: "Sunset Point (Hidden Beach)",
      nextStop: "Gandhi Mandapam / Memorial",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.0855, lng: 77.5380 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "Sunset coastal line clear",
      routeDeviation: false,
      sectionCrowd: { front: 35, middle: 44, rear: 39 },
      doorStatus: {
        frontDoorCrowd: 30,
        middleDoorCrowd: 38,
        rearDoorCrowd: 28,
        isSafeToDepart: true,
        warningMessage: "Scenic seaside view service operating comfortably."
      },
      stopsServed: ["stop_kk_sunset", "stop_kk_beach", "stop_kk_gandhi"],
      driverName: "G. Kannan",
      driverRating: 4.9,
      conductorName: "V. Ravi",
      platformBay: "Sunset Pavilion",
      approxJourneyTime: "18 min"
    },

    // --- CITY TRANSIT CORRIDOR BUSES (Preserved & Enhanced) ---
    {
      id: "27B",
      regNo: "TN-72-N-1234",
      routeNo: "27B",
      routeName: "Junction → Palayamkottai Market",
      routeNameTa: "சந்திப்பு → பாளையங்கோட்டை மார்க்கெட்",
      routeNameHi: "जंक्शन → पालयमकोट्टई मार्केट",
      origin: "Tirunelveli Junction",
      destination: "Palayamkottai Market",
      corridorId: "junction-palai",
      isTouristFriendly: false,
      isVerifiedRoute: true,
      serviceType: "Ordinary City Service",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 46,
      seated: 32,
      standing: 14,
      availableSeats: 0,
      crowdPercentage: 92,
      crowdLevel: "overcrowded",
      currentSpeed: 32,
      etaMinutes: 2,
      currentStopIndex: 1,
      currentStop: "Vannarpettai Checkpost",
      nextStop: "Murugankurichi Signal",
      previousStop: "Tirunelveli Junction",
      currentLocation: { lat: 8.7230, lng: 77.7245 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 4,
      delayReason: "High boarding delay at Vannarpettai junction bottleneck",
      routeDeviation: false,
      sectionCrowd: { front: 88, middle: 95, rear: 91 },
      doorStatus: {
        frontDoorCrowd: 88,
        middleDoorCrowd: 92,
        rearDoorCrowd: 94,
        isSafeToDepart: false,
        warningMessage: "High footboard crowd near rear exit. Boarding lock recommended."
      },
      stopsServed: ["stop_1", "stop_2", "stop_3", "stop_4"],
      upcomingPredictions: [
        { stop: "Murugankurichi Signal", current: 92, predicted: 96, boarders: 9, alighters: 5 },
        { stop: "Palayamkottai Market", current: 96, predicted: 84, boarders: 6, alighters: 14 }
      ],
      hourlyCrowdTrend: [
        { hour: "6 AM", crowd: 25 }, { hour: "7 AM", crowd: 58 }, { hour: "8 AM", crowd: 94 },
        { hour: "9 AM", crowd: 96 }, { hour: "10 AM", crowd: 70 }, { hour: "11 AM", crowd: 45 },
        { hour: "12 PM", crowd: 38 }, { hour: "1 PM", crowd: 48 }, { hour: "2 PM", crowd: 42 },
        { hour: "3 PM", crowd: 55 }, { hour: "4 PM", crowd: 68 }, { hour: "5 PM", crowd: 88 },
        { hour: "6 PM", crowd: 95 }, { hour: "7 PM", crowd: 90 }, { hour: "8 PM", crowd: 65 },
        { hour: "9 PM", crowd: 40 }, { hour: "10 PM", crowd: 22 }
      ],
      driverName: "K. Murugesan",
      driverRating: 4.8,
      conductorName: "S. Arumugam",
      platformBay: "Bay 3 (Junction Stand)",
      approxJourneyTime: "20 min"
    },
    {
      id: "27C",
      regNo: "TN-72-N-5678",
      routeNo: "27C",
      routeName: "Junction → Palayamkottai Market",
      routeNameTa: "சந்திப்பு → பாளையங்கோட்டை மார்க்கெட்",
      routeNameHi: "जंक्शन → पालयमकोट्टई मार्केट",
      origin: "Tirunelveli Junction",
      destination: "Palayamkottai Market",
      corridorId: "junction-palai",
      isTouristFriendly: false,
      isVerifiedRoute: true,
      serviceType: "Deluxe City Service",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 23,
      seated: 20,
      standing: 3,
      availableSeats: 12,
      crowdPercentage: 46,
      crowdLevel: "comfortable",
      currentSpeed: 38,
      etaMinutes: 7,
      currentStopIndex: 0,
      currentStop: "Tirunelveli Junction",
      nextStop: "Vannarpettai Checkpost",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.7290, lng: 77.7095 },
      baseFare: 15,
      studentFare: 5,
      seniorFare: 10,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "Running on schedule",
      routeDeviation: false,
      sectionCrowd: { front: 40, middle: 50, rear: 44 },
      doorStatus: {
        frontDoorCrowd: 30,
        middleDoorCrowd: 38,
        rearDoorCrowd: 25,
        isSafeToDepart: true,
        warningMessage: "Doors clear. Boarding operating smoothly."
      },
      stopsServed: ["stop_1", "stop_2", "stop_3", "stop_4"],
      upcomingPredictions: [
        { stop: "Vannarpettai Checkpost", current: 46, predicted: 58, boarders: 8, alighters: 2 },
        { stop: "Murugankurichi Signal", current: 58, predicted: 64, boarders: 6, alighters: 3 }
      ],
      hourlyCrowdTrend: [
        { hour: "6 AM", crowd: 20 }, { hour: "7 AM", crowd: 40 }, { hour: "8 AM", crowd: 65 },
        { hour: "9 AM", crowd: 72 }, { hour: "10 AM", crowd: 50 }, { hour: "11 AM", crowd: 35 },
        { hour: "12 PM", crowd: 30 }, { hour: "1 PM", crowd: 40 }, { hour: "2 PM", crowd: 36 },
        { hour: "3 PM", crowd: 48 }, { hour: "4 PM", crowd: 58 }, { hour: "5 PM", crowd: 70 },
        { hour: "6 PM", crowd: 75 }, { hour: "7 PM", crowd: 65 }, { hour: "8 PM", crowd: 50 },
        { hour: "9 PM", crowd: 30 }, { hour: "10 PM", crowd: 18 }
      ],
      driverName: "P. Sundaram",
      driverRating: 4.9,
      conductorName: "M. Kumar",
      platformBay: "Bay 4 (Junction Stand)",
      approxJourneyTime: "20 min"
    },
    {
      id: "8A",
      regNo: "TN-72-N-9012",
      routeNo: "8A",
      routeName: "Tirunelveli Junction → Pettai Industrial",
      routeNameTa: "திருநெல்வேலி சந்திப்பு → பேட்டை தொழிற்பேட்டை",
      routeNameHi: "तिरुनेलवेली जंक्शन → पेट्टई औद्योगिक",
      origin: "Tirunelveli Junction",
      destination: "Pettai Industrial Estate",
      corridorId: "pettai-ind",
      isTouristFriendly: false,
      isVerifiedRoute: true,
      serviceType: "Ordinary City Service",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 31,
      seated: 24,
      standing: 7,
      availableSeats: 8,
      crowdPercentage: 62,
      crowdLevel: "moderate",
      currentSpeed: 30,
      etaMinutes: 5,
      currentStopIndex: 1,
      currentStop: "Town Nellaiyappar Temple",
      nextStop: "Pettai Industrial Estate",
      previousStop: "Tirunelveli Junction",
      currentLocation: { lat: 8.7360, lng: 77.6950 },
      baseFare: 18,
      studentFare: 6,
      seniorFare: 12,
      acBus: false,
      wheelchairAccessible: false,
      breakdownReported: false,
      delayMinutes: 2,
      delayReason: "Temple festival traffic near car street",
      routeDeviation: false,
      sectionCrowd: { front: 58, middle: 68, rear: 60 },
      doorStatus: {
        frontDoorCrowd: 45,
        middleDoorCrowd: 55,
        rearDoorCrowd: 50,
        isSafeToDepart: true,
        warningMessage: "Doors manageable. Boarding clear."
      },
      stopsServed: ["stop_1", "stop_7", "stop_6"],
      driverName: "T. Muthuraj",
      driverRating: 4.7,
      conductorName: "V. Selvam",
      platformBay: "Bay 1 (Junction Stand)",
      approxJourneyTime: "22 min"
    },
    {
      id: "12D",
      regNo: "TN-72-N-3456",
      routeNo: "12D",
      routeName: "Junction → Medical College Hospital",
      routeNameTa: "சந்திப்பு → மருத்துவக் கல்லூரி மருத்துவமனை",
      routeNameHi: "जंक्शन → मेडिकल कॉलेज अस्पताल",
      origin: "Tirunelveli Junction",
      destination: "Government Medical College Hospital",
      corridorId: "medical-express",
      isTouristFriendly: false,
      isVerifiedRoute: true,
      serviceType: "Superfast Express",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 14,
      seated: 12,
      standing: 2,
      availableSeats: 20,
      crowdPercentage: 28,
      crowdLevel: "comfortable",
      currentSpeed: 42,
      etaMinutes: 11,
      currentStopIndex: 0,
      currentStop: "Tirunelveli Junction",
      nextStop: "Murugankurichi Signal",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.7300, lng: 77.7065 },
      baseFare: 20,
      studentFare: 7,
      seniorFare: 14,
      acBus: true,
      wheelchairAccessible: true,
      breakdownReported: false,
      delayMinutes: 0,
      delayReason: "On time / express lane",
      routeDeviation: false,
      sectionCrowd: { front: 22, middle: 32, rear: 26 },
      doorStatus: {
        frontDoorCrowd: 15,
        middleDoorCrowd: 22,
        rearDoorCrowd: 18,
        isSafeToDepart: true,
        warningMessage: "Doors clear. Very spacious."
      },
      stopsServed: ["stop_1", "stop_3", "stop_4", "stop_5"],
      driverName: "R. Chelladurai",
      driverRating: 4.95,
      conductorName: "A. Pandian",
      platformBay: "Bay 6 (Junction Stand)",
      approxJourneyTime: "18 min"
    },
    {
      id: "19B",
      regNo: "TN-72-N-4321",
      routeNo: "19B",
      routeName: "Tirunelveli Town Circular",
      routeNameTa: "திருநெல்வேலி நகர சுற்று தடம்",
      routeNameHi: "तिरुनेलवेली टाउन सर्कुलर",
      origin: "Tirunelveli Junction",
      destination: "Tirunelveli Town Nellaiyappar",
      corridorId: "town-circular",
      isTouristFriendly: false,
      isVerifiedRoute: true,
      serviceType: "Ordinary City Service",
      capacity: 50,
      seatingCapacity: 32,
      standingCapacity: 18,
      currentPassengers: 27,
      seated: 22,
      standing: 5,
      availableSeats: 10,
      crowdPercentage: 54,
      crowdLevel: "comfortable",
      currentSpeed: 0,
      etaMinutes: 22,
      currentStopIndex: 0,
      currentStop: "Town Nellaiyappar Temple",
      nextStop: "Tirunelveli Junction",
      previousStop: "Starting Point",
      currentLocation: { lat: 8.7350, lng: 77.6980 },
      baseFare: 12,
      studentFare: 4,
      seniorFare: 8,
      acBus: false,
      wheelchairAccessible: true,
      breakdownReported: true,
      delayMinutes: 18,
      delayReason: "Minor engine overheat check at Town Car Street. Backup vehicle on standby.",
      routeDeviation: true,
      doorStatus: {
        frontDoorCrowd: 35,
        middleDoorCrowd: 40,
        rearDoorCrowd: 30,
        isSafeToDepart: false,
        warningMessage: "Engine inspection in progress. Boarding paused."
      },
      stopsServed: ["stop_1", "stop_7"],
      driverName: "S. Kannan",
      driverRating: 4.85,
      conductorName: "J. Peter",
      platformBay: "Bay 5 (Town Stand)",
      approxJourneyTime: "25 min"
    }
  ],

  // 4-Scale Crowd Thresholds (as specifically required in Section 3)
  // 0–60% Comfortable | 61–75% Moderate | 76–90% Crowded | 91–100% Overcrowded
  crowdConfig: {
    comfortable: {
      min: 0,
      max: 60,
      label: "Comfortable",
      labelTa: "வசதியானது / இடமுள்ளது",
      labelHi: "आरामदायक / स्थान उपलब्ध",
      badgeClass: "badge-comfortable",
      color: "#10b981",
      icon: "fa-circle-check",
      advice: "Plenty of seats available. Comfortable boarding."
    },
    moderate: {
      min: 61,
      max: 75,
      label: "Moderate",
      labelTa: "மிதமான கூட்டம்",
      labelHi: "मध्यम भीड़",
      badgeClass: "badge-moderate",
      color: "#f59e0b",
      icon: "fa-triangle-exclamation",
      advice: "Getting crowded. Few seats left, standing space open."
    },
    crowded: {
      min: 76,
      max: 90,
      label: "Crowded",
      labelTa: "அதிக கூட்டம்",
      labelHi: "अधिक भीड़",
      badgeClass: "badge-crowded",
      color: "#f97316",
      icon: "fa-circle-exclamation",
      advice: "Very crowded. Minimal seating. Consider next alternative."
    },
    overcrowded: {
      min: 91,
      max: 100,
      label: "Overcrowded",
      labelTa: "அதிதீவிர நெரிசல்",
      labelHi: "अत्यधिक भीड़ / चढ़ने से बचें",
      badgeClass: "badge-overcrowded",
      color: "#ef4444",
      icon: "fa-ban",
      advice: "Extremely crowded! Footboard risk. Wait for next alternative bus."
    }
  },

  getCrowdLevel: function(percentage) {
    if (percentage <= 60) return "comfortable";
    if (percentage <= 75) return "moderate";
    if (percentage <= 90) return "crowded";
    return "overcrowded";
  },

  // 32-Seat Blueprint Schema generator
  createSeatLayout: function(bus) {
    const seats = [];
    const totalSeated = bus.seated;
    let occupiedCounter = 0;

    for (let i = 1; i <= 32; i++) {
      let type = "general";
      let label = "General";
      let icon = "fa-user";

      if (i >= 1 && i <= 4) {
        type = "women";
        label = "Women Reserved";
        icon = "fa-female";
      } else if (i === 5 || i === 6) {
        type = "pregnant";
        label = "Pregnant / Nursing Mothers";
        icon = "fa-baby";
      } else if (i === 7 || i === 8) {
        type = "elderly";
        label = "Senior Citizen";
        icon = "fa-person-cane";
      } else if (i === 29 || i === 30) {
        type = "disabled";
        label = "Differently Abled";
        icon = "fa-wheelchair";
      }

      const isOccupied = occupiedCounter < totalSeated;
      if (isOccupied) occupiedCounter++;

      seats.push({
        id: `S${i}`,
        number: i,
        type: type,
        label: label,
        icon: icon,
        occupied: isOccupied,
        passengerName: isOccupied ? `Passenger #${100 + i}` : null
      });
    }

    return seats;
  },

  // Deterministic Nearby POI Generator for ANY real user GPS coordinates
  // Ensures the map NEVER looks empty when live browser location is permitted!
  generateNearbyPoisForUser: function(userLat, userLng) {
    return [
      {
        id: "user_poi_1",
        name: "Metro Transit Stop",
        category: "Bus Stops",
        lat: userLat + 0.0035,
        lng: userLng + 0.0028,
        distance: "380 m",
        description: "Primary municipal connecting bus bay.",
        icon: "fa-bus"
      },
      {
        id: "user_poi_2",
        name: "City Central Hospital",
        category: "Hospitals",
        lat: userLat - 0.0042,
        lng: userLng + 0.0031,
        distance: "550 m",
        description: "Multi-specialty healthcare facility with 24/7 emergency bay.",
        icon: "fa-hospital"
      },
      {
        id: "user_poi_3",
        name: "Government Arts & Science College",
        category: "Colleges",
        lat: userLat + 0.0055,
        lng: userLng - 0.0045,
        distance: "780 m",
        description: "Higher secondary and undergraduate academic campus.",
        icon: "fa-graduation-cap"
      },
      {
        id: "user_poi_4",
        name: "Heritage Clock Tower & Bazaar",
        category: "Landmarks",
        lat: userLat - 0.0025,
        lng: userLng - 0.0038,
        distance: "420 m",
        description: "Historic town landmark surrounded by shopping market.",
        icon: "fa-monument"
      },
      {
        id: "user_poi_5",
        name: "Central Railway Terminal",
        category: "Stations",
        lat: userLat + 0.0080,
        lng: userLng + 0.0065,
        distance: "1.1 km",
        description: "Mainline intercity rail station connecting express trains.",
        icon: "fa-train"
      },
      {
        id: "user_poi_6",
        name: "City Center Shopping Complex",
        category: "Shopping",
        lat: userLat - 0.0065,
        lng: userLng - 0.0020,
        distance: "720 m",
        description: "Retail and commercial bazaar hub.",
        icon: "fa-bag-shopping"
      }
    ];
  },

  // Seed Data for Lost & Found
  lostAndFoundItems: [
    { id: "lf_1", item: "Blue Leather College Bag", bus: "1A", date: "Today, 09:30 AM", location: "Rear Row Seat S28", description: "Contains notebooks and water bottle.", contact: "TNSTC Depo Care (Demo)" },
    { id: "lf_2", item: "Titan Wrist Watch", bus: "27B", date: "Yesterday, 04:15 PM", location: "Conductor Seat Bay", description: "Silver metal strap with white dial.", contact: "Station Master Office (Demo)" },
    { id: "lf_3", item: "Red Umbrella with Wooden Handle", bus: "2A", date: "22 Sep, 11:00 AM", location: "Front Luggage Shelf", description: "Found near driver cabin.", contact: "Lost & Found Cell" }
  ],

  // Recent Trips Seed
  recentTrips: [
    { from: "Kanyakumari Bus Stand", to: "Vivekananda Ferry Area", busNo: "1A", time: "Today 10:15 AM", fare: "₹15" },
    { from: "Kanyakumari Beach", to: "Sunset Point", busNo: "4B", time: "Yesterday", fare: "₹15" },
    { from: "Tirunelveli Junction", to: "Palayamkottai Market", busNo: "27B", time: "21 Sep", fare: "₹15" }
  ],

  // Fare Matrix between main stops (in INR ₹)
  fareMatrix: {
    "stop_kk_stand": { "stop_kk_beach": 10, "stop_kk_ferry": 10, "stop_kk_gandhi": 10, "stop_kk_sunset": 15, "stop_kk_suchindram": 15, "stop_kk_vatta": 18, "stop_kk_padma": 30, "stop_kk_mathur": 35, "stop_kk_nagercoil": 22 },
    "stop_kk_beach": { "stop_kk_stand": 10, "stop_kk_ferry": 5, "stop_kk_gandhi": 5, "stop_kk_sunset": 12, "stop_kk_suchindram": 18, "stop_kk_vatta": 15 },
    "stop_1": { "stop_2": 10, "stop_3": 12, "stop_4": 15, "stop_5": 20, "stop_6": 18, "stop_7": 12, "stop_8": 15 }
  }
};

window.RideSenseData = RideSenseData;
